# Generated by Django 4.1.3 on 2022-11-05 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
