# Generated by Django 4.1.3 on 2022-11-05 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 18, 22, 51, 33, 124932), null=True),
        ),
    ]
